data_path: 
 - data/data/extended/events2020/events/eng-5613032.json
dataset_class: json
dataset_config: {}
builder_class: langchain_singleton
builder_config:
  model_type: ollama
  model: llama3.1:70b
  max_retries: 5
merger_class: langchain_abstraction_singleton
merger_config:
  model_type: ollama_embeddings
  model: llama3.1:70b
